package pg.gipter.core.model;

public enum NamePatternValue {
    CURRENT_DATE,
    CURRENT_YEAR,
    CURRENT_WEEK_NUMBER,
    CURRENT_MONTH_NAME,
    CURRENT_MONTH_NUMBER,
    START_DATE,
    START_DATE_YEAR,
    START_DATE_MONTH_NAME,
    START_DATE_MONTH_NUMBER,
    START_DATE_WEEK_NUMBER,
    END_DATE,
    END_DATE_YEAR,
    END_DATE_MONTH_NAME,
    END_DATE_MONTH_NUMBER,
    END_DATE_WEEK_NUMBER
}
