services:
  release-java11:
    build:
      context: .
      dockerfile: ./java11.Dockerfile
      args:
        - VERSION=${VERSION}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      no_cache: true
    container_name: gipter_release-11
  release-java8:
    build:
      context: ./.
      dockerfile: ./java8.Dockerfile
      args:
        - VERSION=${VERSION}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      no_cache: true
    container_name: gipter_release-8
    depends_on:
      - release-java11